#!/bin/bash

DIRECTORIO="/home/kris/Descargas"

LOG_FILE="/home/kris/lab2/Archivo_Log.txt"

if [ ! -d "$DIRECTORIO" ]; then
  echo "El directorio no existe: $DIRECTORIO"
  exit 1
fi

if [ ! -e "$LOG_FILE" ]; then
  touch "$LOG_FILE"
fi

inotifywait -m -e create,modify,delete "$DIRECTORIO" |
while read -r directory_event; do
  FECHA_HORA=$(date "+%Y-%m-%d %H:%M:%S")
  
  echo "$FECHA_HORA - Evento: $directory_event" >> "$LOG_FILE"
done
